services:
- name: playbackproblems-http
  type: web
  env: docker
  dockerfilePath: ./backend/Dockerfile
  dockerContext: ./backend
  dockerCommand: yarn run -s start:http
  region: oregon
  envVars:
  - fromGroup: playbackproblems-gcp-resources
  - fromGroup: playbackproblems-github
  - key: REDIS_HOST
    fromService:
      name: playbackproblems-redis
      type: pserv
      property: host
  - key: REDIS_PORT
    fromService:
      name: playbackproblems-redis
      type: pserv
      property: port
  - key: DB_HOST
    fromDatabase:
      name: playbackproblems-primary
      property: host
  - key: DB_PORT
    fromDatabase:
      name: playbackproblems-primary
      property: port
  - key: DB_NAME
    fromDatabase:
      name: playbackproblems-primary
      property: database
  - key: DB_USERNAME
    fromDatabase:
      name: playbackproblems-primary
      property: user
  - key: DB_PASSWORD
    fromDatabase:
      name: playbackproblems-primary
      property: password
    

- name: playbackproblems-jobs
  type: worker
  env: docker
  dockerfilePath: ./backend/Dockerfile
  dockerContext: ./backend
  dockerCommand: yarn run -s start:jobs
  region: oregon
  envVars:
  - fromGroup: playbackproblems-gcp-credentials
  - fromGroup: playbackproblems-gcp-resources
  - fromGroup: playbackproblems-github
  - key: REDIS_HOST
    fromService:
      name: playbackproblems-redis
      type: pserv
      property: host
  - key: REDIS_PORT
    fromService:
      name: playbackproblems-redis
      type: pserv
      property: port
  - key: DB_HOST
    fromDatabase:
      name: playbackproblems-primary
      property: host
  - key: DB_PORT
    fromDatabase:
      name: playbackproblems-primary
      property: port
  - key: DB_NAME
    fromDatabase:
      name: playbackproblems-primary
      property: database
  - key: DB_USERNAME
    fromDatabase:
      name: playbackproblems-primary
      property: user
  - key: DB_PASSWORD
    fromDatabase:
      name: playbackproblems-primary
      property: password

- name: playbackproblems-redis
  type: pserv
  env: docker
  region: oregon
  repo: https://github.com/render-examples/redis.git
  disk:
    name: redis-data
    mountPath: /var/lib/redis
    sizeGB: 10

databases:
- name: playbackproblems-primary
  databaseName: playbackproblems
  ipAllowList:
  - source: 96.233.63.33/32
    description: ed - FiOS

envVarGroups:
- name: playbackproblems-gcp-credentials
  envVars:
  - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
    sync: false
- name: playbackproblems-gcp-resources
  envVars:
  - key: VIDEO_BUCKET_NAME
    sync: false
- name: playbackproblems-github
  envVars:
  - key: GITHUB_ACCESS_TOKEN
    sync: false