# GCE-flavored ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: playbackproblems-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
  - http:
    paths:
      - path: /*
        backend:
          serviceName: playbackproblems-http
          servicePort: 13000
---