---
### REDIS SERVICE DEFINITION ##################################################
# TODO: does this all belong in one file?

apiVersion: v1
kind: Service
metadata:
  name: playbackproblems-redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: playbackproblems-redis

---

### REDIS STATEFUL SET/APPLICATION CONFIGURATION ##############################
# TODO: persistent volume claim?
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: playbackproblems-redis
spec:
  selector:
    matchLabels:
      app: playbackproblems-redis
  serviceName: redis
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      labels:
        app: playbackproblems-redis
    spec:
      containers:
        - name: redis
          image: redis:5-alpine
          imagePullPolicy: Always # do we actually want this?
          args: []
          env: []
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 6379
              name: redis
